export type Job = {
  id: number;
  title: string;
  company: string;
  location: string;
  tags: string[];
  description: string;
  logo: string;
};

export const jobs: Job[] = [
  {
    id: 1,
    title: 'Frontend Developer',
    company: 'TechNova',
    location: 'Remote',
    tags: ['React', 'JavaScript', 'CSS'],
    description: 'Work on modern web applications with React and TypeScript.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 2,
    title: 'Backend Engineer',
    company: 'DataNest',
    location: 'San Francisco, CA',
    tags: ['Node.js', 'API', 'MongoDB'],
    description: 'Build scalable backend services and APIs.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 3,
    title: 'UI/UX Designer',
    company: 'PixelCraft',
    location: 'New York, NY',
    tags: ['Figma', 'Sketch', 'UI'],
    description: 'Design user interfaces and experiences for web and mobile.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 4,
    title: 'DevOps Engineer',
    company: 'CloudOps',
    location: 'Remote',
    tags: ['AWS', 'Docker', 'CI/CD'],
    description: 'Manage cloud infrastructure and deployment pipelines.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 5,
    title: 'Full Stack Developer',
    company: 'WebWorks',
    location: 'Austin, TX',
    tags: ['React', 'Node.js', 'SQL'],
    description: 'Develop full stack web applications.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 6,
    title: 'Mobile Developer',
    company: 'Appify',
    location: 'Seattle, WA',
    tags: ['React Native', 'iOS', 'Android'],
    description: 'Build cross-platform mobile apps.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 7,
    title: 'QA Engineer',
    company: 'TestLab',
    location: 'Remote',
    tags: ['Testing', 'Automation', 'Selenium'],
    description: 'Automate and execute test cases for web apps.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 8,
    title: 'Product Manager',
    company: 'Prodigy',
    location: 'Boston, MA',
    tags: ['Agile', 'Scrum', 'Leadership'],
    description: 'Lead product development teams and manage roadmaps.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 9,
    title: 'Data Scientist',
    company: 'InsightAI',
    location: 'Chicago, IL',
    tags: ['Python', 'ML', 'Data Analysis'],
    description: 'Analyze data and build machine learning models.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 10,
    title: 'Security Analyst',
    company: 'SecureNet',
    location: 'Remote',
    tags: ['Security', 'SIEM', 'Incident Response'],
    description: 'Monitor and respond to security incidents.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 11,
    title: 'Cloud Architect',
    company: 'SkyHigh',
    location: 'Denver, CO',
    tags: ['Azure', 'Cloud', 'Architecture'],
    description: 'Design and implement cloud solutions.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 12,
    title: 'Business Analyst',
    company: 'BizLogic',
    location: 'Remote',
    tags: ['Analysis', 'Requirements', 'Stakeholders'],
    description: 'Gather requirements and analyze business processes.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 13,
    title: 'AI Engineer',
    company: 'NeuroTech',
    location: 'San Jose, CA',
    tags: ['AI', 'Deep Learning', 'Python'],
    description: 'Develop AI-powered applications and models.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 14,
    title: 'Technical Writer',
    company: 'DocuMentor',
    location: 'Remote',
    tags: ['Writing', 'Docs', 'API'],
    description: 'Create technical documentation and guides.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 15,
    title: 'System Administrator',
    company: 'SysOps',
    location: 'Dallas, TX',
    tags: ['Linux', 'Networking', 'Servers'],
    description: 'Maintain and monitor IT systems.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 16,
    title: 'Marketing Specialist',
    company: 'Marketly',
    location: 'Remote',
    tags: ['SEO', 'Content', 'Digital Marketing'],
    description: 'Plan and execute digital marketing campaigns.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 17,
    title: 'Support Engineer',
    company: 'HelpDesk',
    location: 'Miami, FL',
    tags: ['Support', 'Customer', 'Troubleshooting'],
    description: 'Provide technical support to customers.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 18,
    title: 'Game Developer',
    company: 'FunGames',
    location: 'Remote',
    tags: ['Unity', 'C#', 'Game Design'],
    description: 'Develop and design engaging games.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 19,
    title: 'Network Engineer',
    company: 'NetLink',
    location: 'Atlanta, GA',
    tags: ['Networking', 'Cisco', 'Firewall'],
    description: 'Design and maintain network infrastructure.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 20,
    title: 'Sales Engineer',
    company: 'SalesPro',
    location: 'Remote',
    tags: ['Sales', 'Tech', 'CRM'],
    description: 'Support sales teams with technical expertise.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 21,
    title: 'Content Creator',
    company: 'CreateHub',
    location: 'Los Angeles, CA',
    tags: ['Content', 'Video', 'Social Media'],
    description: 'Produce and manage digital content.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 22,
    title: 'Scrum Master',
    company: 'AgileWorks',
    location: 'Remote',
    tags: ['Scrum', 'Agile', 'Facilitation'],
    description: 'Facilitate agile ceremonies and remove blockers.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 23,
    title: 'Database Admin',
    company: 'DataKeep',
    location: 'Houston, TX',
    tags: ['SQL', 'Database', 'Admin'],
    description: 'Manage and optimize database systems.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 24,
    title: 'Mobile QA',
    company: 'AppTesters',
    location: 'Remote',
    tags: ['QA', 'Mobile', 'Automation'],
    description: 'Test and automate mobile applications.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 25,
    title: 'Web Analyst',
    company: 'Weblytics',
    location: 'Portland, OR',
    tags: ['Analytics', 'Web', 'SEO'],
    description: 'Analyze web traffic and user behavior.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 26,
    title: 'IT Support',
    company: 'TechAssist',
    location: 'Remote',
    tags: ['IT', 'Support', 'Helpdesk'],
    description: 'Assist users with IT issues and troubleshooting.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 27,
    title: 'Cloud Support',
    company: 'CloudHelp',
    location: 'Remote',
    tags: ['Cloud', 'Support', 'AWS'],
    description: 'Support cloud-based applications and users.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 28,
    title: 'SEO Specialist',
    company: 'RankUp',
    location: 'Remote',
    tags: ['SEO', 'Google', 'Content'],
    description: 'Optimize websites for search engines.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 29,
    title: 'SRE',
    company: 'Reliabix',
    location: 'Remote',
    tags: ['SRE', 'Reliability', 'Monitoring'],
    description: 'Ensure reliability and uptime of services.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 30,
    title: 'AI Product Owner',
    company: 'AIOps',
    location: 'Remote',
    tags: ['AI', 'Product', 'Owner'],
    description: 'Own the roadmap for AI products.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 31,
    title: 'Penetration Tester',
    company: 'PentestPro',
    location: 'Remote',
    tags: ['Security', 'PenTest', 'Ethical Hacking'],
    description: 'Test systems for vulnerabilities.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 32,
    title: 'Data Engineer',
    company: 'PipeData',
    location: 'Remote',
    tags: ['Data', 'ETL', 'Python'],
    description: 'Build and maintain data pipelines.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 33,
    title: 'Cloud Consultant',
    company: 'CloudWise',
    location: 'Remote',
    tags: ['Cloud', 'Consulting', 'Azure'],
    description: 'Advise clients on cloud solutions.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 34,
    title: 'React Developer',
    company: 'Reactify',
    location: 'Remote',
    tags: ['React', 'JavaScript', 'Web'],
    description: 'Develop web apps using React.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 35,
    title: 'Python Developer',
    company: 'PyTech',
    location: 'Remote',
    tags: ['Python', 'Django', 'APIs'],
    description: 'Develop backend services with Python.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 36,
    title: 'Flutter Developer',
    company: 'Flutterly',
    location: 'Remote',
    tags: ['Flutter', 'Dart', 'Mobile'],
    description: 'Build mobile apps with Flutter.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 37,
    title: 'Go Developer',
    company: 'GoWorks',
    location: 'Remote',
    tags: ['Go', 'Backend', 'APIs'],
    description: 'Develop backend services in Go.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 38,
    title: 'Rust Developer',
    company: 'Rustaceans',
    location: 'Remote',
    tags: ['Rust', 'Systems', 'Performance'],
    description: 'Work on high-performance systems with Rust.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 39,
    title: 'Java Developer',
    company: 'JavaGen',
    location: 'Remote',
    tags: ['Java', 'Spring', 'Backend'],
    description: 'Develop enterprise applications in Java.',
    logo: '/logos/placeholder.svg',
  },
  {
    id: 40,
    title: 'PHP Developer',
    company: 'PHPro',
    location: 'Remote',
    tags: ['PHP', 'Laravel', 'Web'],
    description: 'Build web applications with PHP and Laravel.',
    logo: '/logos/placeholder.svg',
  },
]; 